config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # set root for sign out

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    root "homes#index"
    resources :users, only: [:index]
    resources :groups do
      resources :records, only: [:index, :new, :create, :show, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true
  validates :image, presence: true

  has_many :records, dependent: :delete_all
  belongs_to :author, class_name: 'User'

  def total_records
    records.size
  end

  def total_records_amount
    records.sum(:amount)
  end
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/record.rb
class Record < ApplicationRecord
  validates :name, presence: true
  validates :amount, numericality: { only_integer: false, greated_than_or_equal_to: 0 }

  has_many :groups, through: :records
  belongs_to :group
  belongs_to :author, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, presence: true

  has_many :groups, foreign_key: 'author_id'
  has_many :records, foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmable)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[manage edit update destroy]

  # GET /groups
  def index
    @groups = current_user.groups
  end

  # GET /groups/1
  def show
    @groups = current_user.groups
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :image, :author_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  def index
    return unless user_signed_in?

    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Logged in successfully' }
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[show edit update destroy]

  # GET /records
  def index
    set_group
    @records = Record.where(author_id: current_user.id).where(group_id: params[:group_id])
  end

  # GET /records/1
  def show; end

  # GET /records/new
  def new
    set_group
    @record = Record.new
  end

  # GET /records/1/edit
  def edit; end

  # POST /record
  def create
    set_group
    @record = current_user.records.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to group_records_path(@group), notice: 'Record was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  def update
    set_record

    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to record_url(@record), notice: 'Record was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  def destroy
    set_group
    @record.destroy

    respond_to do |format|
      format.html { redirect_to group_records_path(@group), notice: 'Record was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_record
    @record = Record.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  # Only allow a list of trusted parameters through.
  def record_params
    params.require(:record).permit(:name, :amount, :group_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource_name)
    flash[:notice] =
      'A message with a confirmation link has been sent to your email address.
      Please follow the link to activate your account.'
    session_path(resource_name)
  end

  def after_inactive_sign_up_path_for(resource_name)
    flash[:notice] =
      'A message with a confirmation link has been sent to your email address.
      Please follow the link to activate your account.'
    session_path(resource_name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.user_created.deliver_later
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_avatar(image)
    if image.present?
      image_tag(url_for(image), alt: 'icon', class: 'thumbnail icon-img')
    else
      image_tag('Gosave.png', alt: 'icon', class: 'thumbnail icon-img')
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<section class="container col-10">
  <%= form_with(model: group) do |form| %>
    <% if group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name,  required: true, class: "form-control" %>
    </div>

    <div class="category-box mb-3">
      <%= form.label :icon, class: "unit-label", style: "display: block" %>
      <%= form.file_field :image, required: true %>
    </div>

    <%= form.hidden_field :author_id, value: current_user.id %>

    <div class="text-center">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="category mb-3 d-flex border">
  <div class="icon p-2">
    <%= group_avatar(group.image) %>
  </div>
  <div class="flex-fill p-2">
    <div class="d-flex justify-content-between">
      <p><%= group.name %></p>
      <b>$<%= group.total_records_amount %></b>
    </div>
    <p class="text-secondary">Transactions: <%= group.total_records %></p>
    <p class="text-secondary"><%= group.created_at.strftime('%d %b %Y') %></p>
  </div>
</div>

app/views/groups/edit.html.erb
<nav class="navbar p-3 mb-5 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", :back, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>Edit Category</h3>
    <%= render "layouts/menu" %>
  </div>
</nav>

<%= render "form", group: @group %>

app/views/groups/index.html.erb
<nav class="navbar p-3 navbar-light">
  <div class="container-fluid">
    <div></div>
    <h3>Categories</h3>
    <%= render "layouts/menu" %>
  </div>
</nav>

<section id="groups" class="container-fluid">
  <%= render "layouts/alerts" %>

  <div class="container my-5">
    <% @groups.each do |group| %>
      <%= link_to group_records_path(group), class: "text-decoration-none text-dark" do %>
        <%= render group %>
      <% end %>
    <% end %>
  </div>
</section>

<footer class="mt-auto p-3 border">
  <div class="text-center border border-white rounded">
    <%= link_to "Add Category", new_group_path, class: "text-decoration-none p-2 text-white new-btn" %>
  </div>
</footer>

app/views/groups/new.html.erb
<nav class="navbar p-3 mb-5 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", :back, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>New Category</h3>
    <%= render "layouts/menu" %>
  </div>
</nav>

<%= render "form", group: @group %>

app/views/groups/show.html.erb
<nav class="navbar p-3 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", groups_path, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>Categories</h3>
    <%= render "layouts/menu" %>
  </div>
</nav>

<section id="groups" class="container-fluid">
  <%= render "layouts/alerts" %>

  <div class="container my-5">
    <% @groups.each do |group| %>
      <%= link_to edit_group_path(group), class: "text-decoration-none text-dark" do %>
        <%= render group %>
      <% end %>
      <div class="text-end mb-3">
        <%= button_to "Delete", group, method: :delete, class: "btn btn-outline-danger" %>
      </div>
    <% end %>
  </div>
</section>

<div>
</div>

app/views/homes/index.html.erb
<section class="container-fluid p-0 sectionn">
    <div class="home d-flex flex-column justify-content-between">
        <div class="text-center logo_wrapper">
            <div>
                <%= image_tag('masive.png', class: 'logo thumbnail icon-img') %>
            </div>
            <h1 class="logo-text">Masive</h1>
        </div>
        <div class="button-Wrapper">
            <div class="text-center border border-white">
                <%= link_to "Log in", new_user_session_path, class: "text-decoration-none p-2  text-white new-btn" %>
            </div>
            <div class="text-center border border-white">
                <%= link_to "Sign up", new_user_registration_path, class: "text-decoration-none p-2 text-white new-btn" %>
            </div>
        </div>
    </div>
</section>

app/views/layouts/_alerts.html.erb
<% if notice || alert %>
    <div class="container mt-5 col-12 text-center alert alert-success alert-dismissible fade show" role="alert">
        <p class="notice m-0"><%= notice %></p>
        <p class="alert m-0"><%= alert %></p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_menu.html.erb
<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
        <li class="nav-item">
            <%= link_to "Home", groups_path, class: "text-decoration-none nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Manage", "/groups/show", class: "text-decoration-none nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-decoration-none nav-link" %>
        </li>
    </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>MASIVE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/records/_form.html.erb
<section class="container col-10">
  <%= form_with(url: group_records_path, model: record) do |form| %>
    <% if record.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

        <ul>
          <% record.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, class: "form-control"  %>
    </div>

    <div class="mb-3">
      <%= form.label :amount, style: "display: block" %>
      <%= form.text_field :amount, class: "form-control"  %>
    </div>

    <%= form.hidden_field :group_id, value: group.id %>

    <div class="text-center">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/records/_record.html.erb
<div id="<%= dom_id record %>" class="container my-3 py-2 border">
  <div class="col-12 py-2 d-flex justify-content-between">
    <p class="m-0"><%= record.name %></p>
    <b class="m-0">$<%= record.amount %></b>
  </div>
</div>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link_to "Show this record", @record %> |
  <%= link_to "Back to records", records_path %>
</div>

app/views/records/index.html.erb
<nav class="navbar p-3 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", groups_path, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>Transactions</h3>
    <%= render "layouts/menu" %>
  </div>
</nav>

<div id="records" class="container-fluid p-0">
  <%= render "groups/group", group: @group %>
  <%= render "layouts/alerts" %>

  <% @records.each do |record| %>
    <%= link_to group_record_path(record.group_id, record.id), class: "text-decoration-none text-dark" do %>
      <%= render record %>
    <% end %>
  <% end %>
</div>

<footer class="mt-auto p-3 border">
  <div class="text-center border border-white rounded">
    <%= link_to "New Transaction", new_group_record_path(@group), class: "text-decoration-none p-2 text-white new-btn" %>
  </div>
</footer>

app/views/records/new.html.erb
<nav class="navbar p-3 mb-5 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", :back, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>New Transaction</h3>
    <%= render "layouts/menu" %>
  </div>
</nav>

<%= render "form", record: @record, group: @group %>

app/views/records/show.html.erb
<nav class="navbar p-3 navbar-light">
  <div class="container-fluid">
    <%= link_to "<", :back, class: "text-decoration-none fs-3 px-2 text-white" %>
    <h3>Transaction</h3>
    <%= render "layouts/menu" %>
  </div>
</nav>
<div class="container my-5">
  <%= render @record %>

  <div class="text-end mb-3">
    <%= button_to "Delete", group_record_url(@record.group_id, @record.id), method: :delete, class: "btn btn-outline-danger" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>